// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace VSIXProject1
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject1.0488df96-2fcd-4b29-8cd9-a383c21e9af3";
        public const string Name = "VSIXProject1";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Cynthia Z E MacLeod (C3D)";
        public const string Tags = "";
    }
}
