// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject2
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject2.5394C4AE-8DEC-4245-96C5-AAD3088E2A6F";
        public const string Name = "VSIXProject2";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Cynthia Z E MacLeod (C3D)";
        public const string Tags = "";
    }
}
